title: "Alice Zhang"
logo: "/images/241001_Headshots_Senate_AAN227-27.jpg"
description: >
  <div style="text-align: center; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; font-size: 16px; margin-top: 10px;">
    <a href="https://www.linkedin.com/in/alice-zhangg" target="_blank" style="margin: 0 10px; color: #0077b5; text-decoration: none;">
      ğŸŒ LinkedIn
    </a> |
    <a href="pdf/Resume-Alice_Zhang.pdf" target="_blank" style="margin: 0 10px; color: #d6336c; text-decoration: none;">
      ğŸ“„ Resume
    </a> |
    <a href="https://www.github.com/alicez01/" target="_blank" style="margin: 0 10px; color: #6e5494; text-decoration: none;">
      ğŸ’» GitHub
    </a>
  </div>

#theme: jekyll-theme-minimal
sass:
  style: compressed

include:
  - assets/css

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default
      css: "/assets/css/style.css"
